### ISSUE TITLE
Command to dump the active RXG file(s) into current logfile?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#98] opened 2021-03-03 10:01 UTC
In my experience, stations sometime have badly calibrated noise diodes (especially the geodetic stations). Within EVN (and perhaps also VGOS at some point), someone parse the Tsys in FS logfile together with RXG-file data (gain curve) and produce amplitude calibration files (e.g. ANTAB). If the Tsys are wrong, or the GAIN data are wrong, then the result will be wrong.

If one does an ONOFF measurement as part of pre-check setup, then there is an assessment there of the quality of the calibration. The analyst can inspect the logfile and see this, and doing ONOFF is hence good practice.

However, upon discovering there's something wrong, the analyst cannot fix this without extensive communication with the stations. This may be required anyway, but things would be simplified if there was a command which could be included in e.g. exper_initi which would dump the active RXG file(s) into the current logfile. In this way, the analyst could see the Tcal and DPFU/GAIN data used by the FS for the Tsys calculations. This would enable "backwards" calculation in case the Tcal is wrong, which could then be fixed by using the ONOFF values (ignoring one-shot RFI scatter etc.). It would also mean one could track RXG changes through experiment logs. 

Appending the RXG logfile data to the FS logfile means a bit more info, but a few dozen lines of text (typical RXG file) will not matter much given the length of logfiles anyway.

So, perhaps there is one already, but I'd like a single command which will dump the active RXG files to the current FS-logfile (perhaps with an optinal argument of dumping the info in another file than the current logfile if that was desired for some reason).

**Comment by wehimwich** [comment] 2021-03-03 17:31
I think this issue is addressed in 10.0.0, please check [Logging rxg fles ](https://nvi-inc.github.io/fs/releases/10/0/changes_10.0.0.html#logrxg) in the [FS 10.0.0 changes](https://nvi-inc.github.io/fs/releases/10/0/changes_10.0.0.html) document. I will close this issue for now, but feel free to re-open it or another on this topic. Some additional comments are given below.

I added this feature with some reluctance. I think it is needed for troubleshooting, but I think it can cause problems downstream. I like the EVN's model for handling _.rxg_ files, which I understand to be to re-reduce the raw count data from the log with an up to date _.rxg_ file afterwards. This has the advantage that if an accurate gain calibration is not available at the time of the observation, an updated gain calibration can be applied later. This gives the station flexibility to deal with its own constraints and a path to recover if it can't finish the gain calibration before the observation.

If a fixed data path is developed that depends on the _.rxg_ file data being part of the log, then a station without an up to date gain calibration at the time of observing would have to be excluded. This would also mean that it would be difficult to process historical data by adding even a rudimentary gain calibration.

Perhaps a compromise solution would be to use the (latest) _.rxg_ file data from the log to re-process the raw data, but allow an external _.rxg_ file to override what is in the log.

**Closed by wehimwich** 2021-03-03 17:31 UTC

**Comment by varenius** [comment] 2021-03-03 19:15
Fair enough. Actually, I agree with you - I prefer station personel (with intimate knowledge of the antenna and any recent hardware changes) to do this part of the calibration. But, various forces within the IVS seems to like it otherwise. My compromise would be to at least include the information to make it possible to check if things are OK (i.e. run ONOFF as part of pre-check procedure). Having the RXG file does allow someone later on to derive calibration factors without consulting the station, that is true. But, perhaps it could also have the added benefit of allowing more insight into what the problem could be at the analysis stage. Such as "oh, the RXG file has changed, I better ask the station why". Well, we'll see what comes of this, but good that the functionality exists. As with all abilities, they can be used for good and bad :).

**Comment by haavee** [comment] 2021-03-04 06:13
I'll add one argument for including the rxg data in the log file: sometimes stations can't tell us which rxg file was used during an experiment ...

**Comment by wehimwich** [comment] 2021-03-04 13:57
This should be solved for stations that install FS 10. I didn't know this was an issue.

I am a little surprised it is an issue actually. If you reducing the data from scratch for the raw counts, which _.rxg_ file was used at the station should be of little or no interest. The primary use of Tsys at the station is for monitoring system performance between SEFD measurements. The Tcal values can be off by a lot as long as the station knows how to interpret them. Even then, you don't need absolute Tcal values to calculate the SEFDs. Am I missing something?

**Comment by varenius** [comment] 2021-03-04 18:29
No you are not missing anything. Except:
- Some people assume that the "tsys" lines in the FS log files are "the truth" and that any RXG file they find somewhere is "the right one". Obviously this is not true, and using raw TPI values with the "known to be correct" RXG file is the way to go. Easier said, than done, apparently.
- I have made your exact point about Tsys and Tcal, and the goal being SEFD for >1 year now in the geodetic community. People still do not get this point, and/or are confused for various reasons. I commonly hear that "tsys" is what we need. I agree this is not true, SEFD is what we need (and Tcal/DPFU(gain)/Tsys ca be whatever the want to be as long as they consistently form the ratio SEFD when we need it). I have been tasked with giving a summary lecture about VLBI ampcal in the coming weeks, and I will try to make this point (among others)

**Comment by wehimwich** [comment] 2021-03-07 14:33
Now I regret adding the _.rxg_ file information to the log file.

I guess it is confusing that the FS log contains facts like the counts,  but also other things that may be "incorrect" (but can still be useful). The Tsys values, and now the _.rxg_ file information used to derived them, being the pre-eminent examples of the latter. The confusion perhaps is further compounded by the "incorrect" Tsys values in the log possibly being better than nothing for calibration even if they aren't the best.

With possibly wrong, or just out of date, _.rxg_ file information in the log, downstream users have everything they need to blissfully calculate poor SEFDs. I think the EVN system of using a separate path for _.rxg_ file information is wise in this regard. The information needs to be curated; just using what happens to be in the FS log can cause trouble. A way to prevent that is to not include the _.rxg_ file information in the log at all. That would be unfortunate. As I said before it would be useful for troubleshooting after the fact. However, maybe the confusion that it can cause downstream outweighs that.

If you can make headway on communicating how the calibration scheme works, it will be a boon to the community. With all classes taught at TOW, I would have guessed that it was under control. Apparently not. I've had to deal with the misunderstanding of this issue here. There was an urgent engineering project that would have tried to make very accurate absolute noise diode temperature measurements because that is "necessary" to calibrate the data for imaging. It might be a useful exercise, but not for the intended purpose. I managed to stop it, but whether the message really sank in, I don't know. Maybe a way to frame the issue is that you don't need Tsys data, you need the count data and _.rxg_ file information (via different paths).
