### ISSUE TITLE
How to get DBBC3 BBC Tsys numbers in "System temperatures" window?

### ISSUE THREAD

**Issue by varenius** [nvi-inc/fs#138] opened 2021-08-25 14:31 UTC
Reading https://nvi-inc.github.io/fs/releases/10/0/dbbc3.html#_tsys_measurements which I assume is current for 10.0 release, I cannot find guidance on how to get DBBC3 Tsys values in the System temperature monitor window. It starts with a VC column (not BBC). If I run tpicd=no,1000 and tpicd=tsys I get Tsys values in the logfile after some time. And, some values appear in the System temperatures window. But, I only ever get the 14 VC lines. I thought there was a way to a) get BBC lines, and b) cycle through the 64 BBCs?

Side note: In the linked document, it says in section 2.9 that "As a result, effective Tsys measurements for observations won’t be possible until there is support for multicast data." I think multicast support is now working, so it should be mentioned here?

**Comment by varenius** [comment] 2021-08-25 14:33
Additionally, a related comment (sorry for multiple things in the same ticket, but they are closely related): I have forgotten how/where to define the multicast setup for DBBC3 in FS10. Could someone please remind me, and/or add to documentation=

**Comment by varenius** [comment] 2021-08-28 09:57
Maybe related: I decided to reset the DBBC3, and run my procedure calls from scratch just to ensure I didn't forget anything. And now, suddenly, it does not work! I get error trying to run the core3h commands:
```
2021.240.09:38:30.96&core3h_vgos/core3h_mode0=begin,
2021.240.09:38:30.96&core3h_vgos/core3h_mode1=,0xcccccccc,2,,
2021.240.09:38:30.96&core3h_vgos/core3h_mode2=,0xcccccccc,2,,
2021.240.09:38:30.96&core3h_vgos/core3h_mode3=,0x33333333,2,,
2021.240.09:38:30.96&core3h_vgos/core3h_mode4=,0x33333333,2,,
2021.240.09:38:30.96&core3h_vgos/core3h_mode5=,0x33333333,2,,
2021.240.09:38:30.96&core3h_vgos/core3h_mode6=,0x33333333,2,,
2021.240.09:38:30.96&core3h_vgos/core3h_mode7=,0x33333333,2,,
2021.240.09:38:30.96&core3h_vgos/core3h_mode8=,0x33333333,2,,
2021.240.09:38:30.96&core3h_vgos/core3h_mode0=end
2021.240.09:38:34.40?ERROR dr -618(   1)
2021.240.09:38:34.40/core3h_mode1/,0xcccccccc,2,(64.000),128000000,off,vsi1
2021.240.09:38:34.40?ERROR dr -601
2021.240.09:38:37.85?ERROR dr -618(   2)
2021.240.09:38:37.85/core3h_mode2/,0xcccccccc,2,(64.000),128000000,off,vsi1
2021.240.09:38:37.85?ERROR dr -602
2021.240.09:38:41.29?ERROR dr -618(   3)
2021.240.09:38:41.29/core3h_mode3/,0x33333333,2,(64.000),128000000,off,vsi1
2021.240.09:38:41.29?ERROR dr -603
2021.240.09:38:44.74?ERROR dr -618(   4)
2021.240.09:38:44.74/core3h_mode4/,0x33333333,2,(64.000),128000000,off,vsi1
2021.240.09:38:44.74?ERROR dr -604
2021.240.09:38:48.20?ERROR dr -618(   5)
2021.240.09:38:48.20/core3h_mode5/,0x33333333,2,(64.000),128000000,off,vsi1
2021.240.09:38:48.20?ERROR dr -605
2021.240.09:38:51.65?ERROR dr -618(   6)
2021.240.09:38:51.65/core3h_mode6/,0x33333333,2,(64.000),128000000,off,vsi1
2021.240.09:38:51.65?ERROR dr -606
2021.240.09:38:55.10?ERROR dr -618(   7)
2021.240.09:38:55.10/core3h_mode7/,0x33333333,2,(64.000),128000000,off,vsi1
2021.240.09:38:55.10?ERROR dr -607
2021.240.09:38:58.56?ERROR dr -618(   8)
2021.240.09:38:58.56/core3h_mode8/,0x33333333,2,(64.000),128000000,off,vsi1
2021.240.09:38:58.56?ERROR dr -608
```
To the best of my knowledge I did the same now as yesterday when it worked, but I must have made some different setting somewhere. Unfortunately I don't know what the error messages mean. Could someone enlighten me? I attach the full log of commands I sent.
[tt2.log](https://github.com/nvi-inc/fs/files/7070518/tt2.log)

**Comment by wehimwich** [comment] 2021-08-29 14:31
Your time setting method may work. You should check with Sven whether it is suitable or not. There is a time setting procedure in [Time sync](https://nvi-inc.github.io/fs/drafts/dbbc3_ops.html#_time_sync). Sven, somewhat reluctantly I would say (and with no other suggestion), agreed that that method may work. He may like your method better, or at least think it is no worse. The criteria that he agreed should be sufficient to verify that time is properly set are also listed in the section linked to above. He really only wanted time set by the boot configuration (or the not yet available new command for this). 

Not to be pedantic, but the error from `end,force` is the command telling you it can't do its job until the time is synced. That is expected. The text of the `Failed` message is coming from the DBBC3. I thought it that could be utilized conveniently as a reminder to sync.

You are looking at the (old) _monit3_ Tsys display window. That is limited to 16 BBCs (and four IFs for DBBC2). For the DBBC3 (because there are so many channels, and other information), there is a new one, _monit7_. I omitted its setup in the DBBC3  operations document because (again) that is an upgrade step. You can configure _monit7_ to run the same way you are running _monit3_, probably either in _.fvwm2rc_ (for console hot keys) or _stpgm.ctl/clpgm.ctl_ (both in _/usr2/st_) if you are using the display server. There are examples of how to configure each of the those files for the _monit\<n\>_ programs in _st.default/oper/_ and _st.default/control/_, respectively.  For _.fvwm2rc_ you probably want to mimic both the menu and the hot-key setup of the other _monit\<n\>_ programs. You can set the X resources from the examples in _/usr2/fs/st.default/oper/.Xresources_ (your local working copy is _~/.Xresources_). There are suggestions for the proper window size in [Tsys monitor display](https://nvi-inc.github.io/fs/drafts/dbbc3_ops.html#_tsys_monitor_display) (you should use the largest you are likely to need). That section also explains how the window works and the commands you can give it to change its behavior.

I am sorry the installation notes haven't been written yet. In a few days I can try to add some steps for what to do in the operations document to facilitate testing. I think you are almost, maybe even actually, done once _monit7_ is setup. At this point, I think we only have three issues: setup of _equip.ctl_, _dbbc3.ctl_, and _monit7_. If you have run into others, that you may not have mentioned, please let me know.

I don't know why there is no text expansion of the `dr` errors. The error text messages are in the _fserr.ctl_ file.  This is weird because it seems like some more generic problem, but other errors are coming out okay. I do believe I tested these particular errors. Could I get access (discuss by direct email only please) to the system to debug it? In any event the `-60n` errors are that board `n` is not configured correctly. The `-618` errors are that the `vdif_frame` payload size is not correct.

I am a little concerned that the FS is complaining about the payload size. The FS is using `8000`,  but I see `8192` in some of the DBBC3 examples. I don't remember now how we ended up with `8000`, but that is what the FS uses for the FiLa10G as well. Could you check what value you normally use for the DBBC3?

Let's make a list of things that need to be fixed (so far):

- [ ] `help=tpicd` is not displayed properly for DBBC3
- [ ] The help for `tpicd` should say the `tsys` parameter is not useful for multicast systems
- [ ] We need some installation instructions to facilitate testing.
- [ ] Why aren't errors `dr -60x` and `-618` (and may be others) being expanded
- [ ] What is the correct value of  the `vdif_frame` payload size?

None of these seem like stoppers for now. I think I could work on them (and anything else you find in the meantime) towards the end of the coming week.

**Comment by varenius** [comment] 2021-08-29 20:58
Excellent feedback, thank you for taking the time. Sorry I'm a bit careless reading the instructions; my mind wanders a bit recently :).

Re timing: We should not have to reset timing, because we should not have to change the core3h settings - only confirm what is already set. The errors suggest to me that what I am sending is not the same as what is already set. This means either I misunderstood the command (very possible), OR there is some more fundamental mismatch between what the FS believes should be the parameter combination for the current v124 DDC_V 32 MHz BBC VGOS configuration. I noted that my working session happened after I did the "force" on core3hmode and then timesync. So, then I actually configured the DBBC3 and the FS was then happy since the expected and actual configs matched. So the problem seems to be to explain why my assumed matching commands is in fact treated as not matching. More on his further down.

Re "pedantic" - yes, I got that, that's why I tried to timesync :).

Great point with monit3 vs monit7, I had missed that. Will try monit7 as soon as I solve the core3h matching-state issue.

Re fserr.ctl: Turns out that since I'm also running with the code proposed in #132, but locally overwritten instead of properly merged, the DBBC3 error lines were not included in my local copy. Seems we're approaching a state where it would be good to merge several pull requests and branches into main to avoid confusion :). I know good work is being done here, so I'm not pushing anyone - it'll be a few more days before both the dbbc3 testing (me) and #132 responses and other things are sorted. But soon! :)

Re: The help=tpicd should be straight forward, as I believe it was a file suffix change?
The tpicd help could indeed be amended explaining the tsys option as you suggest.

Re Install instructions - well, maybe yes, but I think this is fairly close to being ready enough to be released. Then it could be the "official" instructions. I believe there are only a few (possibly me being confused) points to sort out and then the existing code will already be very useful. So perhaps not worth spending time on making a test-set instructions, if that was your idea. Better focus on the "final" stuff. 

Finally for the vdif_payload size: I'll test a bit more and get back to you. I suspect there is some confusion around the decimation/clock, either in the FS or in my head. Right now I bet on the latter, but I want to prove it by looking at the details. I'll get back later today or tomorrow on this!

**Comment by varenius** [comment] 2021-08-29 21:30
So...using DBBC3 DDC_V 124 for VGOS, it only supports 32 MHz BBCs. So all settings like "samplerate" are coded in the startup config of the FPGAs and we never change it. So I know this is correct in the sense that it has worked for years now. For core3h board 1 I have this config file loaded by the DBBC3 (before any FS interaction):
```
core3_init
core3_mode pfb
regwrite core3 0 0x25252525
regwrite core3 1 0xBFBFBFBF
regwrite core3 9 0
reboot
inputselect vsi1
vsi_bitmask 0xCCCCCCCC
vsi_samplerate 128000000 2
splitmode off
reset
vdif_frame 2 8 8192 ct=off
tengbcfg eth0 ip=10.100.0.200 gateway=10.100.0.1 mac=e4:1d:2d:01:00:92 nm=24
tengbarp eth0 1 e4:1d:2d:f8:f1:a4
tengbarp eth0 11 24:8a:07:b7:c6:1c
tengbarp eth0 15 98:03:9b:99:73:7b
destination 0 10.100.0.11:26411
regupdate vdif_header 3 0 0x03FF0000
timesync
start vdif
sysstat
```
So this is what is actually loaded at the DBBC3. I tried to send the minimum possible command for the FS to realise this is the configuration we already have which for this bear was `core3h_mode1=,0xcccccccc,2,,`. But this didn't work, and FS complained about the VDIF payload size. 

The payload is set by the vdif_frame command, and I see this is set to "8192" above. This is curious, because I would assume 8192 is the total frame size including both payload and header? The latest v124 firmware, including documentation, can be downloaded from https://www.hat-lab.cloud/downloads-dbbc3-ddc/. The example "Setting up the DBBC3" has the same 8192 value. Hm. But, looking in the documentation for the core3h command vdif_frame I read 
"<payload size in bytes> (optional): the total payload size (= frame size without header data) of the VDIF frames". So it really *should* be payload size. However, further down I read: 

> Following rules apply to the properties:
> ...
> 4. Setting an "illegal" payload size is allowed but with the following restrictions:
> a) If a <payload size in bytes> is given that exceeds the maximum supported payload size for this configuration, the payload size is automatically capped to the maximum.
> b) The payload size is ensured to be a multiple of 8 bytes by truncation of the remaining bytes.
> c) If <payload size in bytes> will result in the last frame of a second interval to be incomplete, this frame is silently discarded.

It could be that 8192 is actually a typo in the example config distributed with the firmware, but therefore used at Onsala. And, because of point 4 above this number could actually be set to memory? I'm not sure how to interpret 4a, i.e. if the actual payload size parameter is capped or if the frame payload is capped at creation. IF the parameter can be set to 8192, but FS expects 8000, then this could explain the mismatch. The DBBC3 may still cap the payload to 8000 when sending out the data - which is why everything has "worked for years". I think we need to clarify this with Sven, since 8192 is in the "how to set up DBBC3" but seems like a total frame size to me - so not matching the documentation.

Meanwhile, it's fairly easy to test this - I only have to change 8192 to 8000 in the DBBC3 startup files and reboot. This takes 30 minutes, but if I change this now I can check if it helps tomorrow. I'll report back once I have tested it.

**Comment by varenius** [comment] 2021-08-29 21:38
Hm. Realised I could also check some recorded data. It seems that the data on disk has a total size of 8224 bytes per VDIF frame. If I assume a standard 32 byte header, this would indeed point to a payload of 8192 bytes? I think we need to clarify with Sven what should be the correct value for the payload parameter!

**Comment by varenius** [comment] 2021-08-30 04:28
Good morning! Update: After booting DBBC3 with core3h vdif payload size 8000 bytes instead of 8192, everything works with the core3h_modeX commands! So, it was the payload mismatch. I even get Tsys in the nice monit7 window! (now high because antenna is stowed pointing at the ground):
<img width="259" alt="Screenshot 2021-08-30 at 06 17 59" src="https://user-images.githubusercontent.com/8872291/131285268-6aa0afb4-bd4b-4bda-999e-fa18d46341fd.png">

We'll have to check if there is one "true" value. Otherwise, since this appears to be a configurable parameter (I tested to record data with 8000 set and I now get total frame size of 8032 bytes, so it does what it is told) perhaps one should be able to set the VDIF payload size in dbbc3.ctl or similar? I don't expect this to change very often, but it can be problematic if one assumes something (e.g. 8192) and FS then silently (it never said it was setting the payload size) changes it when running core3hmodeX with "force".

Regarding testing: There is plenty of possibilities for testing on our hardware if you want, we can iterate via email.

**Comment by varenius** [comment] 2021-08-30 04:52
I've been working under the assumption that the FS uses a fixed 8000 payload size. However, Harro pointed out that the logs I sent said
`2021.240.09:38:11.32&exper_initi/mk5=mode=VDIF_8000-8192-64-2`
which set the payload to 8000 in the FS. 
To clarify: The Onsala setting has always been VDIF_8192, I just changed for testing with VDIF_8000 a few days ago. I didn't think the FS would care about this, so I didn't mention that before. Anyway, I just changed back to mk5=mode=VDIF_8192 and my core3h_mode commands still work. This means the FS ignores this mode setting, otherwise it would now complain because the DBBC3 is set to 8000.
@wehimwich Where is the "8000" payload defined for DBBC3 in the FS?

**Comment by haavee** [comment] 2021-08-30 10:01
To the best of my knowledge the FS doesn't actually parse this command but rather forwards it `as-is` to the recorder, without even _looking_ what's following the `mk5=`.

**Comment by varenius** [comment] 2021-08-30 14:32
Did some more digging today. Two main findings:

- Confirmation from quick test yesterday: The FS expects payload 8000, but our DBBC3s hacve 8192. If I reboot DBBC3 with 8000, FS is happy and no complaints. I tried modifying the FS payload limit, but could not make the warnings go away. Maybe I did something wrong (I'm not the one who did the final FS install on our machines), or I missed something. It would be good to discuss how/if to allow other payloads than 8000 for FS DBBC3
- When I run FS with DBBC3 payload 8192, I get the (also pasted above) errors from FS in the core3h_mode sequence:
```
2021.242.14:26:38.00&core3h_vgos/core3h_mode0=begin,
2021.242.14:26:38.00&core3h_vgos/core3h_mode1=,0xcccccccc,2,,
2021.242.14:26:38.00&core3h_vgos/core3h_mode2=,0xcccccccc,2,,
2021.242.14:26:38.00&core3h_vgos/core3h_mode3=,0x33333333,2,,
2021.242.14:26:38.00&core3h_vgos/core3h_mode4=,0x33333333,2,,
2021.242.14:26:38.00&core3h_vgos/core3h_mode5=,0x33333333,2,,
2021.242.14:26:38.00&core3h_vgos/core3h_mode6=,0x33333333,2,,
2021.242.14:26:38.00&core3h_vgos/core3h_mode7=,0x33333333,2,,
2021.242.14:26:38.00&core3h_vgos/core3h_mode8=,0x33333333,2,,
2021.242.14:26:38.00&core3h_vgos/core3h_mode0=end
2021.242.14:26:41.45?ERROR dr -618 Core3h board    1 vdif_frame payload is not correct.
2021.242.14:26:41.45/core3h_mode1/,0xcccccccc,2,(64.000),128000000,off,vsi1
2021.242.14:26:41.45?ERROR dr -601 DBBC3 Core3h board 1 configuration is not correct.
2021.242.14:26:44.90?ERROR dr -618 Core3h board    2 vdif_frame payload is not correct.
2021.242.14:26:44.90/core3h_mode2/,0xcccccccc,2,(64.000),128000000,off,vsi1
2021.242.14:26:44.90?ERROR dr -602 DBBC3 Core3h board 2 configuration is not correct.
2021.242.14:26:48.35?ERROR dr -618 Core3h board    3 vdif_frame payload is not correct.
2021.242.14:26:48.35/core3h_mode3/,0x33333333,2,(64.000),128000000,off,vsi1
2021.242.14:26:48.35?ERROR dr -603 DBBC3 Core3h board 3 configuration is not correct.
2021.242.14:26:51.81?ERROR dr -618 Core3h board    4 vdif_frame payload is not correct.
2021.242.14:26:51.81/core3h_mode4/,0x33333333,2,(64.000),128000000,off,vsi1
2021.242.14:26:51.81?ERROR dr -604 DBBC3 Core3h board 4 configuration is not correct.
2021.242.14:26:55.26?ERROR dr -618 Core3h board    5 vdif_frame payload is not correct.
2021.242.14:26:55.26/core3h_mode5/,0x33333333,2,(64.000),128000000,off,vsi1
2021.242.14:26:55.26?ERROR dr -605 DBBC3 Core3h board 5 configuration is not correct.
2021.242.14:26:58.71?ERROR dr -618 Core3h board    6 vdif_frame payload is not correct.
2021.242.14:26:58.71/core3h_mode6/,0x33333333,2,(64.000),128000000,off,vsi1
2021.242.14:26:58.71?ERROR dr -606 DBBC3 Core3h board 6 configuration is not correct.
2021.242.14:27:02.17?ERROR dr -618 Core3h board    7 vdif_frame payload is not correct.
2021.242.14:27:02.17/core3h_mode7/,0x33333333,2,(64.000),128000000,off,vsi1
2021.242.14:27:02.17?ERROR dr -607 DBBC3 Core3h board 7 configuration is not correct.
2021.242.14:27:05.62?ERROR dr -618 Core3h board    8 vdif_frame payload is not correct.
2021.242.14:27:05.62/core3h_mode8/,0x33333333,2,(64.000),128000000,off,vsi1
2021.242.14:27:05.62?ERROR dr -608 DBBC3 Core3h board 8 configuration is not correct.
```
However: Despite (!) these warnings, the FS then settles into a state where sensible Tsys values are displayed in the monit7 window (I missed this during my first tests above, because I looked at the monit3 window). Also logging with "tpicd=yes,100" and then "tpicd" appears to work. So, it seems I stumbled across this paylod issue, but it is actually not preventing me from getting the tsys data. 

We have discovered things here to investigate further, but I still want to point out that the DBBC3 tsys logging now works - which is very, very nice!

**Comment by wehimwich** [comment] 2021-08-31 11:53
Sorry, I have been away for a bit. There are several topics on this issue. I think the original topic is settled. Even if so, please leave the issue open until I work through the checklist. I will try to address the other contained open topics below, but please open new issues as needed, perhaps more narrowly focused if appropriate. You can of course copy old material from this issue as needed.

Working through posts since the checklist items, these topics seemed to be worth commenting on (let me know if I missed anything):

Timing: With the current state of affairs things will probably be easiest if the DBBC3 boots into the configuration that will be observed with. This may not be practical for astronomy experiments, which use various configurations, but may be for current VGOS observing. If practical, that would most easily satisfy Sven's warnings about re-syncing. Of course just now, VGOS will soon start trying new frequencies. I think you are allowed to change frequencies without re-syncing. Either way, you would either need to make a SNAP procedure to command those frequencies or make a new DBBC3 boot configuration that uses them (if you can pick an arbitrary, pre-canned configuration at DBBC3 boot). _drudg_ can generate a setup procedure (that you could be used as is for this by not using `force`, which only triggers commanding, instead of checking, the Core3H boards), but the VGOS schedules are not in VEX yet.

#132: I am sorry for the proliferation of feature branches. We have a few, particularly the one for the DBC3, that have gone on longer than intended. Anyway, there is just one commit on @mikaellerner's branch. You should be able to cherry-pick it onto your local branch for the DBBC3. I would suggest you start a new local branch before doing that to keep things from getting too tangled up. This topic may have been OBE (Overtaken By Events) since I see the error messages in the most recent post. Normally station specific code should be in _/usr2/st_ to avoid this sort of issue. I am tentatively checking off the "Why aren't errors `dr -60x` and `-618` (and may be others) being expanded" item above. Thanks.

frame_size: I believe `8000` is the right value.  If I am wrong, I will of course make changes. If my memory serves, it is the size without the headers. The FS uses `8000` for the FiLa10G and _jive5ab_. I thought I had worked through this with @haavee, but maybe I came to the wrong conclusion. I also seem to recall that _jive5ab_ pretty much takes any data that is thrown at it and records it (thank you Harro!); the magic string sent is just(?) being used to calculate `rtime?` responses. Of course the data being thrown has to be correct.

Using `8000` fixing the Tsys display: I don't think that is the case. It should only affect the output VDIF, not the TPI. I think the key change was using _monit7_. Additionally, even if you set the DBBC3 to `8192` the FS won't change it unless you use `force` and  it will still tell you if anything else is misconfigured. We don't like to ignore errors, but may be that would expedient until we get the payload size sorted out, which will hopefully be soon. Hmm. Maybe I should remove the _summary_ `-60x` errors. They seem redundant, but I thought it might be better to be explicit since normally it should not come up very often. I guess I won't change it for now.

Yes, the payload size for the DBBC3 is set at https://github.com/nvi-inc/fs/blob/ed/dbbc3/clib/dbbc3_core3h_modex_util.c#L355.

`mk5=`: Yes, the command just passes the data directly to  the recorder and FS does not interpret its meaning. In any event, the recorder setup does not impact the rack (DBBC3, in this case) configuration, nor vice-versa. A correctly constructed FS `fb_mode` (or `mk5c_mode`) command should send the correct magic string. The correct command may be too cumbersome to construct without _drudg_'s help. The real question is whether the payload size should be `8000` or `8192`. If it should be `8192` (or if we need place to decide which is right), please open a new issue.

**Comment by varenius** [comment] 2021-08-31 13:55
@wehimwich My apologies for making this ticket broaden beyond the original topic, which was probably monit7 as you say.

I will file new questions in new tickets, and we can close this one when you think your list of points has been sorted. (Or, you can create new tickets for each point, and then close this one - your choice I think).

Re jive5ab: It will NOT record anything regardless of framesize setting, I explicitly asked Harro recently in https://github.com/jive-vlbi/jive5ab/issues/16. So this matters, and has to match. I'm sorry I confused people here, I was testing multiple things with these logs and the jive5ab/DBBC3 mismatch was not the subject of this ticket ;).

Re frame size: I have only seen 8192 as payload value ever mentioned in DBBC3 documents. I may be wrong, and to me it doesn't matter which value (of course). But we need to figure out if this should premanently be either 8000, 8192 or if it can/should be changed. If changing can happen, FS needs to adopt. I have sent an email to Sven, Gino and friends to see if we can clarify this. Once we get a response, we can open a new issue for whatever action we need. 

To re-iterate, the original "getting tsys values" issue is solved, and Ed can close this ticket as he see fit.

**Comment by wehimwich** [comment] 2021-08-31 14:34
No problem @varenius. All issues should be addressed and discussions can get complicated. I am just try to organize it a little more.

**Comment by haavee** [comment] 2021-08-31 15:39
Let me focus briefly on one issue: the `vdif frame size`. This FiLa10G output parameter *is* settable by the user, specifically through the DBBC[23]/FiLa10G `vdif_frame <bits per channel> <channels per frame> [<vdif frame size>]` command.

The recorders will typically require the frame-size-to-expect to be configured - in the FS <-> jive5ab interaction this is through the "magic mode string", specifically in the `mode=VDIF_xxxx-....` part, the `xxxx` specifies the VDIF payload size in bytes.

The firmware of a DBBC will boot with a pre-defined value for this parameter. The FS can _rely_ on this, but the FS could also _ask_ the firmware what the current value is, and use that to send to the recorder: the `vdif_frame` command without any parameters returns the current configuration.

**Comment by wehimwich** [comment] 2021-09-06 21:37
Coda:

After further discussion on email, the consensus seemed to be that the VDIF frame size should ultimately come from VEX2 schedules (good suggestion @haavee!). That will be possible after VEX2 is in use. It can then be implemented when it is needed. For now, `8000`, as the FS uses, is the correct size for DBBC3 (DDC) and DBBC2/FiLa10G, as confirmed by Sven.

Also at @havee's suggestion, I added an appendix with an interim method for [Handling other VDIF frame sizes](https://nvi-inc.github.io/fs/drafts/dbbc3_ops.html#_handling_other_vdif_frame_sizes) to the DBBC3 document (this link will break when the document is eventually fully merged in). This is just a draft, so please pardon any poor wording or other errors/problems. Please let me know if you see any of either. The method is kind of complicated, but doable. Hopefully we will be able to update the FS to handle this issue before it is needed. We can do something short of the full VEX2 method if that seems appropriate.

I have pushed new commits on the `ed/dbbc3` branch that fix the `help` issues for `tpicd` and also include updated local file examples for installation. Please `pull` that branch to get the latest version. No actual DBBC3 functionality was changed.

I added a [Installation for testing](https://nvi-inc.github.io/fs/drafts/dbbc3_ops.html#_installation_for_testing) appendix to the DBBC3 document. It uses the new example local files. The same caveats about the link breaking, it being a draft, and to please send corrections apply as well.

I will close this issue for now, but feel free of course to add other comments and/or reopen it.

**Closed by wehimwich** 2021-09-06 21:37 UTC
