### ISSUE TITLE
fs time jump to the 2000

### ISSUE THREAD

**Issue by robin-pl** [nvi-inc/fs#171] opened 2022-03-11 06:57 UTC
When observation is running ,the fs time jump to the 2000, we restarted the fs ,but faild to resolve the problems.
So we have to restart the PC ,then it's ok. This problem appeared two or three times in recent years.Now fs version is 9.13.02,in fact old version also appeared the same problem.

**Comment by wehimwich** [comment] 2022-03-11 12:38
How long had it been since the computer was rebooted when the time jumped? There is a well known limitation of the 32-bit arithmetic used for the clock model that causes it to overflow at about 248 days after booting. That is usually the cause of this sort of problem. It is a little surprising that FS computers are going 248 days without being rebooted. We recommend rebooting more often, maybe at least once a month. Rebooting every six months should be enough to prevent this problem.

What model are you using in _time.ctl_? It is usually `rate` or `computer`. The _setcl_ prograrm should warn as day 248  since rebooting approaches, but there was a bug when the model is `computer` that prevented it from issuing the warning. This is covered in issue #56. It has been fixed and will be included in the next release, _10.1.0_.

Discussion #170 has the same initial post as this one. This topic feels more like an "issue" than a "discussion", so I am going to delete the discussion. This issue can be converted to a discussion if that seems better.

**Comment by wehimwich** [comment] 2022-09-29 22:51
There has been no news on this for six months. I think the explanation provided is probably correct (it has been a recurring issue, so we have seen it before) and the fix in #56 has been included in _10.1.0_. If you think this is not the explanation or you think there is another problems, please reopen the issue. I hope you will be able to upgrade soon.

**Closed by wehimwich** 2022-09-29 22:51 UTC
